"""Initial migration

Revision ID: 8eda63d0e041
Revises: 
Create Date: 2025-05-12 13:49:52.540465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8eda63d0e041'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_table('product_sizes')
    op.add_column('order_items', sa.Column('unit_price', sa.Float(), nullable=False))
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.drop_constraint('order_items_ibfk_1', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.drop_column('order_items', 'price')
    op.drop_column('order_items', 'size')
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=False))
    op.add_column('orders', sa.Column('shipping_city', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('shipping_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('shipping_country', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('contact_phone', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('orders', 'payment_method',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CASH', 'CREDIT_CARD', 'BANK_TRANSFER', 'PAYPAL', name='paymentmethod'),
               nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('orders', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'fullname')
    op.drop_column('orders', 'city')
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('discount_percent', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'image')
    op.drop_column('products', 'category')
    op.drop_column('products', 'new_price')
    op.drop_column('products', 'tag')
    op.drop_column('products', 'old_price')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_index('email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'password')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('fullname', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('users', sa.Column('address', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('email', 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.add_column('products', sa.Column('old_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('tag', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('products', sa.Column('new_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('products', sa.Column('category', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('products', sa.Column('image', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'discount_percent')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.add_column('orders', sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('orders', sa.Column('fullname', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('orders', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('orders', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('orders', sa.Column('address', mysql.TEXT(), nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('orders', 'payment_method',
               existing_type=sa.Enum('CASH', 'CREDIT_CARD', 'BANK_TRANSFER', 'PAYPAL', name='paymentmethod'),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('orders', 'notes')
    op.drop_column('orders', 'contact_phone')
    op.drop_column('orders', 'shipping_country')
    op.drop_column('orders', 'shipping_postal_code')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    op.add_column('order_items', sa.Column('size', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('order_items', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_column('order_items', 'unit_price')
    op.create_table('product_sizes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('size', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_sizes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promo_codes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('discount_percent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('min_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'promo_codes', ['code'], unique=True)
    # ### end Alembic commands ### 